typography_spectrum: 0.9160802329424769
color:
  brandStrength: 0.965197901474312
  lightness: 0.7125009160954505
  saturation: 0.5304906414821744
  rhythmicContrast: 0.8777183673810214
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.37448287359438837
author:
  name: Sixto Cancel
  email: sixto@fosteryouthforhillary.com
  url: www.fosteryouthforhillary.com
name: Foster Youth For Hillary
title: Foster Youth for Hillary
